[nizami:chess]
# Nizami'nin Oyunu - Tarihi Satranç Pozisyonu (9. yy)
# Murray 50 (p.284) - as-Suli ve al-Adli
# Beyaz oynar kazanır
# 1. Ag6+ Şh8 2. Kf8+ Şh7 3. Kxh6+ Şg7 4. Vf6+ Şxh6/Şxf8 5. Kh8# mat
startFen = 6k1/5R2/7r/4NQ2/8/1q1n4/R2R4/2K5 w - - 0 1
maxRank = 8
maxFile = 8
