[wsn_gelismis_ag:chess]
# 1. Makro Ölçeklendirme ve Kapalı Devre Topoloji
maxRank = 10
maxFile = 10
cylinder = true

# 2. Dinamik Düğüm Enjeksiyonu (Canlı Ağa Donanım Ekleme)
drop = true

# 3. Seri Veri Aktarımı (Burst Transmission Testi)
# Not: Stres testi için aktif edilmek istenirse başındaki '#' kaldırılır.
# moveCount = 2

# Standart Kuralların İptali
pawn = -
knight = -
bishop = -
rook = -
queen = -

# 4. Donanım ve Sinyal Karakteristikleri (Betza Vektörleri)
customPiece1 = s:K   # Uç Sensör: Çok yönlü, 1 birim iletim sınırı.
customPiece2 = r:W3  # Yönlendirici: Doğrusal hatta maksimum 3 sekme (hop) menzili.
customPiece3 = d:DA  # Ağ Geçidi: Doğrudan engel aşan (Line-of-Sight atlayan) röle düğümü.
customPiece4 = j:I   # Sinyal Bozucu (Jammer): Çevresindeki veri paketlerini bloke eden kara delik düğümü.

# 5. Merkezi Toplama Noktası (Sink Node / Hedef Bölge)
promotionPieceTypes = srd
promotionRegionWhite = e5,e6,f5,f6
promotionRegionBlack = e5,e6,f5,f6

# 6. Başlangıç Topolojisi ve Yedek Düğüm Havuzu
startFen = 10/1d1j2j1d1/2s4s2/3r2r3/10/10/3R2R3/2S4S2/1D1J2J1D1/10[SSSRRRDDD] w - - 0 1